[versions]

java = "17"

androidGradle = "8.12.3" # https://developer.android.com/reference/tools/gradle-api
androidCompileSDK = "36"
androidMinimalSDK = "28"

kompress = "1.2.1"
kotlin = "2.2.21" # https://github.com/JetBrains/kotlin/releases
kotlinxIo = "0.8.2" # https://github.com/Kotlin/kotlinx-io/releases
kotlinxBrowser = "0.5.0" # https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-browser
dokka = "2.1.0" # https://github.com/Kotlin/dokka/releases
karmaConventions = "1.8.1" # https://github.com/karmakrafts/karma-conventions/tags
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
fflate = "0.8.2" # https://github.com/101arrowz/fflate/releases

[libraries]

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }

[plugins]

android-library = { id = "com.android.library", version.ref = "androidGradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }